/* Micro Wars — map definitions.
   Grid chars: . plain, f woods, m mountain, r road, = bridge, v river, w sea, s shoal,
   C/B/P neutral city/base/airport, 1/2 HQs, c/e cities P1/P2, b/d bases P1/P2, p/q airports P1/P2. */
'use strict';

const MAPS = [
  {
    id: 'border',
    name: 'Border Clash',
    desc: 'A tight land skirmish. Grab the middle cities fast.',
    grid: [
      '1b...ff...d2',
      '.c..f..f..e.',
      '..rrrrrrrr..',
      '.cr..CC..re.',
      '..r.mCCm.r..',
      '.cr..CC..re.',
      '..rrrrrrrr..',
      '.c..f..f..e.',
      '.b...ff...d.',
    ],
    units: [
      { t: 'INF', p: 0, x: 2, y: 0 }, { t: 'INF', p: 0, x: 1, y: 1 },
      { t: 'INF', p: 1, x: 9, y: 0 }, { t: 'INF', p: 1, x: 10, y: 1 },
    ],
  },
  {
    id: 'river',
    name: 'River Divide',
    desc: 'Two bridges decide everything. Artillery loves this map.',
    grid: [
      '.c...fvf...e..',
      '1b...rvr...d.2',
      '.crrrr=rrrre..',
      '.b...rvr...d..',
      '..f..rvr..f...',
      '.c...rvr...e..',
      '.crrrr=rrrre..',
      '..m..rvr..m...',
      '.C...fvf...C..',
      '..f...v...f...',
    ],
    units: [
      { t: 'INF', p: 0, x: 1, y: 0 }, { t: 'INF', p: 0, x: 2, y: 2 },
      { t: 'INF', p: 1, x: 11, y: 0 }, { t: 'INF', p: 1, x: 10, y: 2 },
    ],
  },
  {
    id: 'island',
    name: 'Island Front',
    desc: 'Air power rules the channel. Hold the center isle.',
    grid: [
      '1b..c.wwww.e..d2',
      '.p.r..wwww..r.q.',
      '..rr.swwwws.rr..',
      '.crr..wCCw..rre.',
      '..r..swBBws..r..',
      '..r..swBBws..r..',
      '.crr..wCCw..rre.',
      '..rr.swwwws.rr..',
      '.b.r..wwww..r.d.',
      '.c..f.wwww.f..e.',
      '..m...wwww...m..',
      '.C....wwww....C.',
    ],
    units: [
      { t: 'INF', p: 0, x: 2, y: 0 }, { t: 'INF', p: 0, x: 1, y: 2 }, { t: 'TCOPTER', p: 0, x: 1, y: 1 },
      { t: 'INF', p: 1, x: 13, y: 0 }, { t: 'INF', p: 1, x: 14, y: 2 }, { t: 'TCOPTER', p: 1, x: 14, y: 1 },
    ],
  },
  {
    id: 'valley',
    name: 'Iron Valley',
    desc: 'Mountain walls and one long road. Rockets echo here.',
    grid: [
      'mm1b......d2mmm',
      'mc.r..CC..r.emm',
      'mc.r.m..m.r..em',
      '.crrrrrrrrrre..',
      '...r.f..f.r....',
      'mb.r..CC..r.dmm',
      'm..rrrrrrrr..mm',
      'mc...m..m...emm',
      'mm.f..CC..f.mmm',
      'mmm..C..C..mmmm',
      'mmmm......mmmmm',
    ],
    units: [
      { t: 'INF', p: 0, x: 3, y: 1 }, { t: 'MECH', p: 0, x: 2, y: 0 },
      { t: 'INF', p: 1, x: 11, y: 1 }, { t: 'MECH', p: 1, x: 12, y: 0 },
    ],
  },
  {
    id: 'grand',
    name: 'Grand Field',
    desc: 'The long war: full production on a wide open front.',
    grid: [
      '1bc...f..ww..f.....',
      'bp.r..c..ww..e..r..',
      '..rr..r.swws.r..rr.',
      '.crrrrrrr==rrrrrre.',
      '..r..f.r.ww.r.f..r.',
      '.cr.m..rBwwBr..m.re',
      'cr.m..rBwwBr..m.re.',
      '.r..f.r.ww.r.f..r..',
      '.crrrrrr==rrrrrrre.',
      '.rr..r.swws.r..rr..',
      '..r..c..ww..e..r.qd',
      '.....f..ww..f...ed2',
    ],
    units: [
      { t: 'INF', p: 0, x: 2, y: 0 }, { t: 'INF', p: 0, x: 0, y: 1 }, { t: 'APC', p: 0, x: 1, y: 2 },
      { t: 'INF', p: 1, x: 16, y: 11 }, { t: 'INF', p: 1, x: 18, y: 10 }, { t: 'APC', p: 1, x: 17, y: 9 },
    ],
  },
];

/* Campaign missions: fixed setups, intro text, and tuned AI. */
const CAMPAIGN = [
  {
    id: 'c1',
    name: 'Boot Camp',
    intro: [
      'Commander! Enemy scouts crossed the border overnight.',
      'Take your infantry and push them back.',
      'TIP: Tap a unit to see its range, tap a tile to move, then choose an action.',
      'TIP: Attack from Woods or Mountains for a defense boost.',
    ],
    objective: 'Destroy all enemy units.',
    grid: [
      '.c...f....',
      '1..r...f..',
      '.rrr.m....',
      '..r...r.e.',
      '.fr.rrr..2',
      '..rrr..f..',
      '.c...m....',
    ],
    startFunds: [0, 0],
    noProduction: true,
    units: [
      { t: 'INF', p: 0, x: 1, y: 1 }, { t: 'INF', p: 0, x: 1, y: 2 }, { t: 'MECH', p: 0, x: 0, y: 3 },
      { t: 'INF', p: 1, x: 7, y: 3 }, { t: 'INF', p: 1, x: 8, y: 5 }, { t: 'INF', p: 1, x: 6, y: 2, hp: 50 },
    ],
  },
  {
    id: 'c2',
    name: 'Armored Fist',
    intro: [
      'Enemy armor is rolling toward our outpost.',
      'Your tanks are faster — flank them. Artillery strikes from afar but cannot move and fire on the same turn.',
      'TIP: Check the damage forecast before committing to an attack.',
    ],
    objective: 'Destroy all enemy units.',
    grid: [
      '.c..f.....e.',
      '1.rr...m....',
      '..r..f...f..',
      '.crrrrrrr.e.',
      '..r..f...r.2',
      '..m....rrr..',
      '.c...f.r..e.',
    ],
    startFunds: [0, 0],
    noProduction: true,
    units: [
      { t: 'TANK', p: 0, x: 1, y: 2 }, { t: 'TANK', p: 0, x: 2, y: 4 }, { t: 'ARTY', p: 0, x: 1, y: 3 }, { t: 'INF', p: 0, x: 0, y: 2 },
      { t: 'TANK', p: 1, x: 9, y: 2 }, { t: 'RECON', p: 1, x: 8, y: 5 }, { t: 'ARTY', p: 1, x: 10, y: 4 }, { t: 'MECH', p: 1, x: 9, y: 6 },
    ],
  },
  {
    id: 'c3',
    name: 'Supply Lines',
    intro: [
      'This valley feeds the whole front. Whoever holds its cities funds their war machine.',
      'Capture properties with Infantry and Mechs. Each one pays 1,000G every day.',
      'TIP: APCs can carry foot soldiers deep into enemy territory.',
    ],
    objective: 'Capture the enemy HQ, or destroy all enemy units.',
    grid: [
      '1b...ff...d2',
      '.c..f..f..e.',
      '..rrrrrrrr..',
      '.cr..CC..re.',
      '..r.mCCm.r..',
      '.cr..CC..re.',
      '..rrrrrrrr..',
      '.c..f..f..e.',
      '.b...ff...d.',
    ],
    startFunds: [3000, 5000],
    units: [
      { t: 'INF', p: 0, x: 2, y: 0 }, { t: 'INF', p: 0, x: 1, y: 1 }, { t: 'APC', p: 0, x: 1, y: 2 },
      { t: 'INF', p: 1, x: 9, y: 0 }, { t: 'INF', p: 1, x: 10, y: 1 }, { t: 'TANK', p: 1, x: 9, y: 2 },
    ],
  },
  {
    id: 'c4',
    name: 'Air Superiority',
    intro: [
      'The enemy scrambled attack copters over the channel.',
      'Anti-Air shreds anything that flies. Fighters own the sky. Bombers erase ground armies.',
      'TIP: B-Copters hit hard but crumble against Anti-Air fire.',
    ],
    objective: 'Capture the enemy HQ, or destroy all enemy units.',
    grid: [
      '1b..c.wwww.e..d2',
      '.p.r..wwww..r.q.',
      '..rr.swwwws.rr..',
      '.crr..wCCw..rre.',
      '..r..swBBws..r..',
      '..r..swBBws..r..',
      '.crr..wCCw..rre.',
      '..rr.swwwws.rr..',
      '.b.r..wwww..r.d.',
      '.c..f.wwww.f..e.',
      '..m...wwww...m..',
      '.C....wwww....C.',
    ],
    startFunds: [8000, 10000],
    units: [
      { t: 'INF', p: 0, x: 2, y: 0 }, { t: 'AA', p: 0, x: 1, y: 2 }, { t: 'BCOPTER', p: 0, x: 1, y: 1 }, { t: 'INF', p: 0, x: 3, y: 8 },
      { t: 'INF', p: 1, x: 13, y: 0 }, { t: 'BCOPTER', p: 1, x: 14, y: 1 }, { t: 'BCOPTER', p: 1, x: 12, y: 2 }, { t: 'INF', p: 1, x: 12, y: 8 },
    ],
  },
  {
    id: 'c5',
    name: 'Final Stand',
    intro: [
      'This is it, Commander. Their main force is dug in across the great field.',
      'They out-fund us and they know it. Fight smart: hold chokepoints, mass your fire, and strike their HQ.',
      'Good luck. The whole army is yours.',
    ],
    objective: 'Capture the enemy HQ, or destroy all enemy units.',
    grid: [
      '1bc...f..ww..f.....',
      'bp.r..c..ww..e..r..',
      '..rr..r.swws.r..rr.',
      '.crrrrrrr==rrrrrre.',
      '..r..f.r.ww.r.f..r.',
      '.cr.m..rBwwBr..m.re',
      'cr.m..rBwwBr..m.re.',
      '.r..f.r.ww.r.f..r..',
      '.crrrrrr==rrrrrrre.',
      '.rr..r.swws.r..rr..',
      '..r..c..ww..e..r.qd',
      '.....f..ww..f...ed2',
    ],
    startFunds: [10000, 16000],
    units: [
      { t: 'INF', p: 0, x: 2, y: 0 }, { t: 'INF', p: 0, x: 0, y: 1 }, { t: 'TANK', p: 0, x: 3, y: 2 }, { t: 'ARTY', p: 0, x: 1, y: 2 },
      { t: 'INF', p: 1, x: 16, y: 11 }, { t: 'INF', p: 1, x: 18, y: 10 }, { t: 'TANK', p: 1, x: 15, y: 9 },
      { t: 'MDTANK', p: 1, x: 16, y: 9 }, { t: 'ARTY', p: 1, x: 17, y: 10 },
    ],
  },
];

if (typeof module !== 'undefined') {
  module.exports = { MAPS, CAMPAIGN };
}
